# Server
quarkus.http.port=8080
quarkus.application.name=financeira
quarkus.application.version=1.0-SNAPSHOT

# Database
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/finance-db
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect

# OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true

# Logging
quarkus.log.level=INFO
quarkus.log.category."br.com.verso".level=DEBUG
